//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiJson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFTdata_ivy
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        //public int ID { get; set; }
        //public string DivisionName { get; set; }
        //public string VPsalesCode { get; set; }
        //public string VPsalesName { get; set; }
        //public string SalesHeadcode { get; set; }
        //public string SalesHeadName { get; set; }
        //public string ZonalHeadCode { get; set; }
        //public string ZonalHeadName { get; set; }
        //public string AreaHeadCode { get; set; }
        //public string AreaHeadName { get; set; }
        //public Nullable<System.DateTime> Date { get; set; }
        //public string DistributorCode { get; set; }
        //public string DistributorName { get; set; }
        //public string DSRCode { get; set; }
        //public string DSRName { get; set; }
        //public string RouteCode { get; set; }
        //public string RouteName { get; set; }
        //public string CustomerCode { get; set; }
        //public string CustomerName { get; set; }
        //public System.TimeSpan Timein { get; set; }
        //public System.TimeSpan Timeout { get; set; }
        //public System.TimeSpan TimeSpent { get; set; }
        //public long TimeSpent_Sec { get; set; }
        //public string PlannedorDeviated { get; set; }
        //public string Orderid { get; set; }
        //public decimal OrderValue { get; set; }
        //public int TLSD { get; set; }
        //public Nullable<System.DateTime> SyncDate { get; set; }
        //public System.TimeSpan SyncTime { get; set; }
        //public string Reason { get; set; }
        //public string Latitude { get; set; }
        //public string Longitude { get; set; }
        //public string GeoFencingDevReason { get; set; }
        //public System.DateTime ReceivedON { get; set; }
        //public string seller_type { get; set; }

        public IEnumerable<Data1> Data { get; set; }
    }

    public class ResponseModel { 
    
        public string statuscode { get; set; }
        public string message { get; set; }
    }

}
